language: generic
matrix:
  include:
    - os: osx
      osx_image: xcode9.3
      dist: trusty
      sudo: required
      env: COCOAPODS_DISABLE_STATS=true ACTION=test  PLATFORM=iOS     DESTINATION='platform=iOS Simulator,name=iPhone 6S'
      script: set -o pipefail && pod install --repo-update && xcodebuild -workspace SQLiteViewer.xcworkspace -scheme SQLiteViewer -destination "$DESTINATION" $ACTION | xcpretty
